sprite $AzureWorker [100x100/16z] {
xTc5aXmX58NXWrsRzt_UE5svJUX98L6-iYtR7mPRmV_WE8v86qK0WDXM0e1iCm9iEoJRBcNRBf_6QQno6hAveHG1tjZWX2-2NJIkRH0giGe0hMm8gclm0G22
hciOBlN2nbTvVQD-quABh6e4V2yHSD5LZOIUQAiQ1JqysL2K-aMNJJO2WCXcZAuosQ2wnEYpoGQgVOs4HXRxX3CkOQeXJrk8K9MP1cwIEH7V29KS0y90Gzzj
e0HlQ3sYdqKZmf69lTiV9PmoUiuhwO-XYgFtLRj3cNiJcMoGVPFTscJNaB46tuPO_0PWlo1ZZN9h-27x_HrbgX7kHx-qJx2EtOcQy9CD6hnBAA1gFYlrdzNB
XXg4IxlckTqIymtsU_TsPON1Xhf6V3o3QR1XSFHfPmSTR2GupyCeOms2awqH_4Htl54HJbxnriPc5fuED7BAn6BbXrCXtD78F2et5n9HeOIMpJGKFLDhxWdU
oxQjaLxVxcQRR4JqKBsWURRnVWt49XiPFURCDB2_GRZ4boaJBh9i7WNL_HBXsKQxiPg9bOKD4pTgL7csuHLag_BgULJgBx2GUU_V4ml_JN-pF8tJE8rasoNO
TW3RPlnB_YUy_t_R_uFZE3u2
}

AzureEntityColoring(AzureWorker)
!define AzureWorker(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureWorker, AzureWorker)
!define AzureWorker(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureWorker, AzureWorker)
