sprite $AzureAutomation [100x100/16z] {
xLa9akGW30jW0qx__xrxfeeXGi6JflTirR7711JBjWoPxTDuuusKmiivzc-md5v94VS3zNKqUM_8BvIgeImKA81KIsC9MlVTjWEwdr6MoPzGgWFRqx1-gm0K
if13nrBPzZnghucTEU9IZZ9AHzqMSRHNbdK93-slfUsN6kEvESADTyyZZaCg32D1Mdob961FXbB9ZnYizOyNNSMKJfSAOJJUTClpIjyD4QHAtVFnHXsXzcdG
VdQZnXAZi4EuXj2KuXtl3wHg78-EZj8FPD1XY8TIj-Q8C6CjGAotEzx8188mGbTZVl2b4Uhs6OlFGm4oZWsxxutZbL2tE2NzqE72ECoItPmZKF0e5N6tARAg
IfAKMyqogHJ3ioX9L3MBGo6i59IAn3TD3JvAfKgN2wERe_0VsxKlPBVVGbzoyxiMcSjQURRoB9CpaqB9KQfw89D00kLmIuLxcJVfyKfJPHIeS_OEZWnH0jAm
NehVgMGw6sMaf8LFJFD8k4cWa0XF9864GIJvdC7duTFf1sA6xbd6WHwxBU0WobQs5w7cAUSSFGN-m1n9BzUNLMKKqNrrqrcpqX2Jyuk0JFqvWLcI0wHtHD7h
rNpjOvOBdf006Z9Jdcd5nSfKx0mU070E6buru9PUZefnck_GDEtmXWYlSEVGX8raPhKQEUrUMuELQcQZqWqYCb8UQgZiuRfMv5AWoZ-zDJpYHAb9ekcws6Xb
Gf4cjp9GK854AGNtGbDmqjXszDuamzMvxMV-GpaUiBH5Qw_DlqHpQp2a6ECH1lOJVHya4kWzXWtVe88EhgiDuOXmII2_8KZDfQcgGiBW_5NJ4KuK99XVI-33
spqOBJgpFjfqcwEGaaXT-auwAceAeoAHC69fctRRcdoekj9Aa21t1KOADsAfc_vSPH5gbEfVpr6aKKd7VgKUJirg09Stl-9t7dWx5mS0EQg7evxsz724RX4G
bqWvSdkKSg0JQ0kZrHNb04FrNG4It2i0TZus1IT7-21DaCjPOP2dmiwrJhz2YC4FMoS1dBwBa69T0-Y3_DhPDp_MWS_1TTZvF5y7F9SaMwiLFr-z1DWNwr7N
bXDtuUt5496u_Gruuusl
}

AzureEntityColoring(AzureAutomation)
!define AzureAutomation(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureAutomation, AzureAutomation)
!define AzureAutomation(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureAutomation, AzureAutomation)
