sprite $AzureWebJobs [70x70/16z] {
lPO7OZCz2uG1DM3U-r_tByWsAx9E-ygJ7iiZCHGjVGABIE-ZzoR2z2jaBdC0sDzCPwSVmXF-4QZGzsaAlmSslXkA9t1TQwd3a-y4nWk-MLCeQVEf1UCV7AHJ
GGRWmHTXFKoTozrnixOPjirVYaGcOcsxStxlO_GMnIiIHieKbWVyNYIj6o4Zfp6zZz5bUa2tB1m1QonzoRJbJym3U-l9eiJou7q1_W6zTQqQyTnnsOt4RH9v
__-q38_wFO2xgQgbROdUgJIlm5TliKXkh164QrMy-u7DoouTxkX4nScrQe4CJu3PFXuV7wmLAmsoS16PJ0M6EsOvYf8ToUCZCtJ3BCuWZBNhFzc-gWsIipPM
B8iJjRJxXRshL3taVRjjMKXoqH0-2huwSoqBunsd5n7ezcqlgUoGCg7wY09ZBfqfqZDTHIRVcRQCRN81aZLsxV0ZYimpUAUkm7KWjvifpSMZvWUW0soPljOu
2gqL5KzAKj8S8BhXakl-AWtRVL3ZAKnawb9bl9eeyvcWKwMN2PM9ePug9uigeyOxlrPHggmQxpmYik-THJsHCw9elE_vCaj4wMvckkP8xY-Agj9BlNmHK1b_
SbHTT83SrAwybO5f97jtG3e_CmV5c49R5dV1SCVi4LhjR_C2VOBXg0Tv7byyK9rDyMRqrqh6A1EJEjBLa06iqNiafdwz4cQ8S-xKkKV8ZIbXZbVxmyPp2WkH
7bwm-emPq02znc5C5CNXvxMc-p2rJ7Y5-ldF2VTzkNOtzrPgiX6kJw6pxH21dGXPSjnKw6rDyNhRsrR9gQ_NGR0SuBCBx19FRh0k5Sk-MPsvZPrt2BKnubTr
RA5tFSzPYb0cUXnWLuPl3IPUI97amyosHq7nberJyZxKQzzsLq6fmjJgh7EtETSemx8oa2gAZ6sqInv1UbM1KcMb2Yw50x_SQkZsI2FRsKKtJzkAJBdRPPUs
rwmsFVX39zc1SrU_lsoLy8qwd1WUe8oncplK95oW_XmZ4dvt617-c3-etbQBCMdbJWgqHmEreoWMlKCSxhrPR7NAcBkhx5zK1k3qdkcOUbwD4-EPexNj8o8n
fa-GXGuS3w6yKmI47FT6tq2aoIXFGHqEQOr-Y3vIoKyHd_HppFtrHiak_1dB0_YQ2dYWz5CKyEulCBFtVeAElBZZUb6bNn4gWoSSGh-d8Iorel9JsfButkZV
uBy
}

AzureEntityColoring(AzureWebJobs)
!define AzureWebJobs(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureWebJobs, AzureWebJobs)
!define AzureWebJobs(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureWebJobs, AzureWebJobs)
