sprite $Gears [100x100/16z] {
xPXd0gKW38G30IoKtF-qsmlg-13psEhtqpO6GYP0_pSF3m_iFcD7AiXtXgbO-GaD8ibFLXg3LEH7OuTROsXgJ75bkatSf9356lAPHINnJOIZRCb-4zogJLNo
WfZhyOiwYNE2Y4PaaLucwaNweKwCzFCdna59UbbfU225RZ1CegRe9VI1wClm3AQLlvLZsP7U5SOCoe2kYGYomr2D1O6ePxmHvpk6glL4e3xOUxV81gOZNYgo
yvzWkeQxd9j5ZjZRou89uGLmsvmwVcUvMN0ZOR8SIJSrPiAiQersOiv_WCQVDbP9CUSZSdV-GzOWsSkrH026jZZ2M6QUPODhEKoq_0bBDPp1grsrtJH_Olkg
1JcZzYXNts9Kazthgitj9j7KB-9w-RAYHXmb_a9PJ18W0ZCpUaD4ngT6h-lDMHK0CtALiX-ZXO80aghXlVQUid6_iijpsarEVnXPUedjNLvHxzMWESpUXLIR
7RDcpmdSCQ1HoUeuwaWiTZvR_KmRRFge3O1FHccI3VG_XzB8Ww9KYHGic9c8W0G5wBfujSSwuKAM3PEfNgs_v-SYN_5d6ik-jIcDSxYTH3bRrUMaixNBugYX
GNwTBRILWE9m-ZDBApz9oB18hq5I0LhA_6wDShJcG0ZihykbDZCTfybVFpUZKzOI9zb-qgn85sD1DzZkvqldPixOpnXgeJk_qHz7Xl4QcTu4zk9KPOiQTzAJ
U2cMtWJB0Kzgy78bEyqWOxNKjbTtlOK6i2QkNR6jeKzZff5mJhEdtyZ3myF3mqS
}

AzureEntityColoring(Gears)
!define Gears(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, Gears, Gears)
!define Gears(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, Gears, Gears)
