sprite $greenway [280x155/16z] {
xDBLbKGX4411j7lpZtXvDfB2K8N_taFz6G00000000000000KDxgWpD6EwppJiFAqCQCFCGSlLsT_9KU-MLqPLQLp8p3npbRBPjdcKUD_7Ic6NjdQV5KYTlz
-9jRPycyGnp7nosobNspr7YoPCxHbn57cPsp7Fx9hzBjodaG9bRd_L_uMoxHgIRkFKcNVyCiRGoMiG0Rro8jvMnSFF__Zh-O5iIYv90ot7WTVpKjraBBdmqD
lpaYZmKTve3AlHPGarzwmEmA_3XTsl0ESlB8_pU0kRkBpNnl3hnNCn_T22m6Ev6Wx0FgsqjCHjLa1yEJpcNaVTK0vf5h6Gm-zeRNk4TDkbMwOSFs7EkkS43X
ejQYoHWOzUuHMGw2n8Y3UWu8M9-XpIjCbxe5pWt3xHrDUM_grMGkJWV6vLmYvO0YayAjIZrxdQUwlZrcutc94k9uVHz9dkeS24orrrBfWK4eB0Lvo6QVbL6z
j_7ZjP4Zn-lPab2gMwUGGX67xhHNMib-HeyW5epS3ujbc86rckPmqYWmWJ4JWgKu69BxCkhRCg8hbLpSmMwGCZkLENdLaXXuZshJcw0sQQ0nPpjvqdpTbq5k
yHQN7KzwEfhUaaTfhg72E31RTcqRDhXjDdD8Q51i14F-cGjaJBFPi1L7FNe2tFEYiMUI5ySw8vSwmUsmWywYnubFu3JTy17d45jDnlmeemr8A8Mr0DsLqVsn
YwjSDr9Pou7WK1Xun7Bdua6xWKSDKvnmPBKqq73Xda3CDYRuV4s1Zq_X7cFARIC9j2U1uL7tScShHP5kqyXyf01OZuHXifC8-KvgIR8RI3ltIjKbd_jC0o8P
w7xwAvhqWRouyZbUqESlTtLxZiSipqYC5KUuA85eloTiQ-c7FZoCL12iw92ih9TWQvdLIWVe0rVLHfwn4QySlyeBauEbeDHh-lE37j1UxsA1qzfGrXnqX-Pq
HUysxT0-UFcpa71JHlUyQ80Of6iWR3lKb9SYo3M5MsacDWEflFW7D3k4vYreD2tcgPwAhhmGYBOQZY_M4S7UvujUDrG3uB70OD2-RDGWmXDUM4Y9MQTN9RCF
zkTKShBb2uF7tD8EqR_7Ix_aKrvYuoNZbDHBaXvqKAJkRdWnvd-TM-aZerSFBwvbn8JnoAp_vOARagJQCOeylOzWw-38MrwqsWx-K5xgCpKpxfON9z8e-WWV
NX88AQEP6_ckkzJMM3U1R_4I-R_KGrwwAHilcvektl5YH9eGz-4dO1boB9EiUEagWdiffAsCljVlmf_miaiBBviyvCMikBIl7iXax4vanZpM6Zgkl6o516-c
6kMBxoC0F-4bVimBqHDnzCo9cU36Bfg6Ozczrv4MKkw7shVUqz_WXN8eBxksd_3Yv33dM9cqVgtFcBFWM2cTcR4_VsgHHykdpGjJJHgFXxpeFUrNqSQo_1Fr
VHqPPzUmSLhqIfSoqbCk-4tSlMqgdamYpn-EptdXQRA9775bc_O9BpZdHxqgnC7mLV30qLod5nilKaZdGVeljUQ1P3a80z566E-__uKtgdZLtt9Wy_Ja8PMV
XKe8uNKNyhiBN5en27cywxhdWZcE_TqbZUcao6yHmBvniV0uNhR4QcHtpuMDMvgbRxDOvW9s2td2qp-vYd5GmKKzPux-OXij6ipMz91BRH7pLpln8ptYmckc
r_SkA1vpcV5ntrQsaIFuuGwUSCaqY1-nfJPlDpp_aiqzmLzn0NkThgMRSwdzBeG7aUy3uULIFLfUPLnniPnRdrTX_Uloi9wHHkhRbFqfbu3BQ68C2JZy2pcI
uSTR9-p4bcAOBAtBAhjBBchat69U2h5mJtjArD6tpFZVSKdjvbxSvVYmxAEMcDXeJjWR5eDULETVpbw4hNnaxGzvpmKRXlJm9TpGTqvqs1XpE-CbYpdHg-R2
JdBjjfEgqzD3BjmdX0u1gCer43CLcT05LJTKTI3PT3DcHFFTxsAw6ouDpfeGB2sPh7XeX650c6sy8lcD9id_T9Hv4Mls8lNYkNN1ROJCXzPSwW091nEdI-J9
0PXC3gr5POq1IsnzHXnkBqXUypje9ZdYb9_5BtwoSL86po_1yu095cRwbM91oMeeh4Oa-Fus9BOnzjqAn8trzhrrU96qJrSh7hvEhpHHZ6EitntxkYHK_hyQ
GPTsqVoerEToIQMkIu_KUiXxP98FQ_zBAebvS_jZSe0bkQ28uUFB7_MYcsqu7VUVxChfeqlvdLzAASR-gIcDKgqVl8kMxW6-S6zVEN24G110gwg1hfxx7zW2
5bcpJhyMlM58Nq-4IVpt0VbSWpYjFxgqfopiRWFCR1AlxdHOEkzmATTsATUVN8uQsCRY2N_Tm6TxlVnnWqlwkx_WQntQQXOGkzlCRExkiq9j79REsrmgItY_
s7lIHsqUai1o8J2J14VcwpBhHfVz83IuX7PQEFr5pSvGSBf8hU-6FSUYsIptk0Z0nmKQhgSyX3KwggeSHDWMHgNj9vTBNvM31C_siY7m8fT6YMttbonxf2k9
_hZAph8-_QKxdUas4RCUE_C9yDoWQGHlSiaLdYwzCeFAh3QhMgWvAoQ4XJr-o9NDfbZjTeVf8O9NkTIAp1BJrG2qyY1209W-BcU-FUiHC5pzvuuCy2wNCMFr
5zdL9BLoBXGflbq4ulZqwV9rRNRNUiIeB8MT9uGOcRRpzou2ELsEo9Kkm7OfPtr2UkoglxYS_dAn2xVB6KTII5dEeDB_S3bnkKjWXogh0SV5VnX7ZH6X88Eu
rWN3JW9WyEMoQm_FsqKZLD7gNfVTBqP46nMiT4hTMNtMkd4V9BxdtKvcx_tbSjbz1hIoQqPdVt8bdKymAsk0BlknugazlynswE8OeztbacDekUm4OjZE4GIx
xHhHdZwhxIGqQuUKOqo6Dh8HGPuzdjV6sQ0C452420QnYayjyOTTrNS7yDxQlhEdz4TxSM0000210Ep_gw4tsgYo5G00000000000000O04
}

AzureEntityColoring(greenway)
!define greenway(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, greenway, greenway)
!define greenway(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, greenway, greenway)
