sprite $iis [100x100/16z] {
xPY9bgCW44NPrwBz_x-T0LyBeKzoxDBCokib14bThOMKYhz2Iygw4xAIJv3fuwG2cq5d4No8_VY658yHlyEmF4Rw4nYBiHYBeLxBti3On6kPVuIXxuY7VYtt
M_DgCHPZCHPZCHPZCHPZCHPZSszcbEIDU2iZQW6zYL6yWDx6YF9OBPLMwdv6qLXfGYxx52MdxcGaqQH2UPpFzZP6UFuyiBZhZ8vmmuGorAz5tS08mv9ORRS4
A_kxAdkHWLX8QaEfZk2eoX2s1SXVP9I6A7LazeL8uh0_lepzKjaC_VbeDbVMQA_K2y4pLN-54JyFaqJSrV0mjHp9O2umckMjEIqQaTlbGBgQbYxl2_cC00Tr
HIKbDfGofGQJ8N4mq9W6JICt8t0SHZoILEW8gxEoasrDOZBC7bgagwBfC18AYnI3WRGPqhLKczfOwvorMjMgSUAeoC1Y9AI_mh8vHsat30l4OJH7nFvXDKSs
zIYqK-4mpEEvQaG6wdmakECmvAD_xCm821bY5JWC-4TsHX6ZN9leVZl3e4dm3q5bNb8U3-Op3349ZBEY4upjDp7QBW5HxKL7vV4WsrUz9kQOpnFnPCpZ9EIk
7N9NZF83WtYvkw46uxCQ33q6E1VsNb9Ex2McyHcCZ0_FUwBygUwVlgrmQZ0FxGU6b0adK2XXR-yD2oElciBk1MchoQ-Ye7kpnQiFVDVgLvra2GRVonm6N3qg
UMUDDiQwwKP1NM78mokc1m0XZpRrzk9KFC9NrVonjOThewyzN7sbwYz-3xSTlMWMptfHWxRuOa-TgwkK4B8x1MEqk-w6UmEgG_lGHs6OUfV5PY00kGsrF2Pq
gphVbhZBzsfnoE14RG9tFNjL5YCkCm2nfTU87jz8SPa123QCMMJ4IQNj9MCZdAkdgLaruhICUotl1AHSeZqA58qKRvEKIicRJ6cjUQP-
}

AzureEntityColoring(IIS)
!define IIS(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, IIS, IIS)
!define IIS(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, IIS, IIS)
