sprite $MSSQLAnalysis [100x100/16z] {
xDPNeeCs48NXSwQFzh_W126kSJeNdFu_-KcVHwBX7zd_aN-6mCy213vgJE2J1eKdx9F2IZuX2F5HWoeak47aPpPBJTVbEXsPeE39p8tl_vnp93nOklnyU_Zi
8DB6do0Kujb1P8mq8I22cSXqyF0aLcE4xuU_9X0-Ymm1DSQFTReAiGPv5b40Jh7eAOMfwEE80Rx-ltfkJeyrqvEJg64beQ6UFKjNFdScXHazWDndibYGFJ6H
55Bs7uPZuyxGI1FSp5mTWBS0WDg93m-FqMEqtsJI6eZYMXShoH040R4QTnbsIou2x4Ce0T2OSJAb-7RUlOZ3a6XRXtL4t_RCRWpIeLo_kQ51R9dXbEOD9Ngh
JAOXrOgz5hpbtzynRTNT2UiyXW2qyKeiswroZ22knnO0uZrB79LZZvfTHY0KsgC5rsl1J6fkcXvZoBgeTW3GMZjck5pewmgRZCqnSWVQ13CEMVXmNCrrdRsM
GNDJ5DOcqHs2eqmiBAyZPW2O9UjaDgLwotY-geWZluoe0Qmaj37JAQJYbBwTWWsxQ2XO0I02Cubf4A-a4--aN3HOlYxYbz3TWYDM4Mzf4nToxpcv5G16jrSR
z8paoLjfu4BHYgqoqBkT-yOmln3_EK6cNZ2wP4sltK6mrZxuGhGLHnIroAjV5knk1r2HdJBd4knf5m4kOdsxf2bnCSlkJjZn6B6szykf55JVNuSg-4uby7aT
sLhMyOfbaT4zHjtu6f82vaN4jMYS2StUklcrvGOmlupCbsvrS_qLctEATGf-4EBhAmxt2uENjI0QW2O1GEEH0LPIaixIVI390oXJug4oIf0sVmg34dE72F0f
muPZ4J2j2Hm3F6H8wnT1Fxw0yAXH0fPEBKQt2G7mKICKKWBGUeoGOzqd3JTOSHjXbF6yBfyop1b1hJ5IiNfu3WbjtpR91VoC8QD6zIZbhvmpUP_OIW7EnW_j
cWTM1J480F_GVDx_m7RCWbrYDmUOMM3JKx3iK8Gi51MRtf4Y3PaIcCVH5MVQIBHeXWwzgWFqoh8ySuUTQx8B25ZAcSEjbs59DjN35xo7iSkXfOT1Dp3kWzJP
8J65pyo1jXiFKb2W31nuAN2sblzPELmA8mKjDwDKcNT5--vv718aNU1XRzZXSB_ReQXmouJ7aRmtLnA6-je_K3cjzEzpM2G_IK-G1wcAi6DK9FCWOphJHlX1
8GsMrPavF89xXRRH5jZH0tKb2wkuD8mTHEGvaT4LiEU6MECkMwfjMe9jyvD7E2jJ01K8KqTA_Ev4GXkwzPk194nEg5lxUJVUrrj4cEcBgMUsM8_mPnLC5HaA
JwHbrswJj3G5DDNCeX5nE_5A4spTD5kuAq93DiTOeswc8gSFRUjslZG-IWQ_w4NEnxV_TWa
}

AzureEntityColoring(MSSQLAnalysis)
!define MSSQLAnalysis(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, MSSQLAnalysis, MSSQLAnalysis)
!define MSSQLAnalysis(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, MSSQLAnalysis, MSSQLAnalysis)
