sprite $Quartz [100x100/16z] {
xC610000082W_QaNgG80002cfJomtGP2A4fzeFrlEETfi5fwydLT1ZFMN0C--aii42hleQgqL9cyX2U0L94el5E9OIUJXS1VAO82DxLKEk8SJuQlo9IBcit7
MOTBQ7f63uMBAi-uEj0xFA5xJtgtKjLhbHx0rE3e8UwDKb4mLed3KTtfKPGy7C6ZbWCHWUvG09G15Y1tnoWcWva73xAbggUZUqyUwMfmoUwpDopkm0ic2ao7
goQQ2yMwzUvWXi7XmCqn5vMSL0KLOysgYQOTeWnk3dJoTJYiss-E6TY1LgbeJXrULSVHzf75pS4THfUPXzmTDHSFLYaoXL18vQ_hu9lQljrT-tZhxW0tRmxV
5t3Kc3BEUOHTvn7Tt5ZWcCUZLpdf0osNaIWLAOEpNgrj_vNpFq8Nku_Cn4MDpeiZgBzYufFm8ZX7LTqPoUdjmehOUv1Tpp5bOnmpxm89MOI8kfuEbHFq8lcz
OxYzkP3SIhPjjN2hbTaTsmV80ZRreFkXe3t295idTWPcisdsk8tDOWUoY2tDBAgRZia-KFalfh9fX8QyWdqSkUwxhw1PMwNhj_RWW0O0001XaFrJs-C35WK0
000S
}

AzureEntityColoring(Quartz)
!define Quartz(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, Quartz, Quartz)
!define Quartz(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, Quartz, Quartz)
