sprite $AzureStorageTable [100x100/16z] {
xPhNkXuX24N7XhBV_ttJ4zAEZAERgrbNf_xhGy5-HVBoebXbML6np5Xru05fJI5uWFB30CgAOi0WTNl6GzfIth83ANYCB7GuEv263GO_323VKNGOf49CsAJm
yjPOoLjQ8U80_hInJ_V2e0SYECAWXk4Nui0fRauR-WKyfNejPSFqNt_zPqjtuEF2SlBM76dg63D7SyBOS3Y1oBR3BqJiElmLNJ_jK7VQM7VuXQZd7V2cZNM7
MuWuu702QHo7E67uZkuwCCbRSnoR4HDO3Yj4dJbKZN--LJMcAxgCcQDiz8VzEuopUMNTNcaEAqIm71Q8i1ro9R0TI16EYBRYztbKxbvWrZdkZ2Kjbn_a36Wk
lxuTGB5VjldgMddZhWQDxVuSrPly0b3xhYaWzbttTcsiFWzOCxI8jGz_3LVuQr4DM5Cd_jwW1-nn0lPg4hpdDEh9Eg_-6O0vHZS0bL_VY0BT6BCmZFoFWt0e
Ctp7_k7ItmwvJHjt3yd4IRuZ_th6SVlCigyvkfUt1WuGS8PS-6VX6d2cd_Xt4ptWZYNWhgW5tdaHyxVmxo0ru2uryU-4Hy3TTi0TlGIyDGXuCr7vRp_qYkJb
vJC
}

AzureEntityColoring(AzureStorageTable)
!define AzureStorageTable(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureStorageTable, AzureStorageTable)
!define AzureStorageTable(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureStorageTable, AzureStorageTable)
