sprite $SyncService [100x100/16z] {
xPdNWhOm24G339FtV-A_Pejha62yzDnjFJAaVR7zu-NbvKL4rG2OgaXx7ZKusJyW7QQF2k3iP-XuI2FcFSPDzWrWluQGRKCETsenzZMejulewzmBJDahKBTp
og5L5UXrK5VKGL6nATbNx4kitySs1kspGrZOTw2q7EzxeDwCEhQLbCDK_g1mRgI5nHLSrE-cfV5-5smkzR7bwLudVyX6kMTbn0yc2lu79fTRZ9QxuJAYcLI6
QaU4iS9uoc-CzThGYdzVF9IZDaSyweNmeazUwRe4JpGKKOtAGbWM_9SHLDWhAuI5u7VHOn2KYVLHvUb-elD2VBqTbYxsFdywol8abtCPd1I2INshxV2VttOL
4SKX-NbOjkh0ZwWm6O6SjmohCz16rgU_mp7FniMc-pHKdVJnQDOzXxHcy_9nJDvmmDSTF3fiFWWnxIsJARZlQE1-LfQEqdizz_alQukfZrsRhWdoKHe69h4Z
dOFKoO64vrEA7oJ5jOHstjlH2X8xEtXQ4ma3pskYBKhqrjhE_p4lIYJO7JGzfIixhHrJzFNJbQPxxQZq9C7oVkxZS9KSJ9ObTf55JmvOgn89_utoGc6z7oKz
b4GZoEKW8Rxufr1-eL-PHnBheKHG-9Hl5-kbC9OqTQuw6Yuaw1UI9kOasgP4ixif4QakuhPy0U1w23m37j-TQO-WwrS9x1Li4cIiCPKR3bhnHWO5HxGTsvEE
Q17sigD-gIKiECgAWJ9rU0eZnS1IHuw5YW6s7SfOaKjGLvGbA2lg4i8288bY_-wI5YbYWWl3T66MGB7z7eUGkc9KNImYLiI8iT29WgB-Vd1FCKuAiS1DMbLH
VryRAUh8Z_VExXZxRgQelpzNCrDLQIV4EIWegiWdhSRBoyjl
}

AzureEntityColoring(SyncService)
!define SyncService(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, SyncService, SyncService)
!define SyncService(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, SyncService, SyncService)
